Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/modules/R1/include/comm_list.h File Reference
comm_list.h File Reference
#include <input.h>
Data Structures
struct s_cmd_struct
Macros
#define MAX_CMD_LIST_LENGTH 50
Typedefs
typedef struct s_cmd_struct cmd_struct_t
Functions
int getNumDaysInMonth (int month, int year)
getNumDaysInMonth is a helper function to allow the easy retrieval of days in a month based on the month input by the user.
int isEmpty (char parameters[][MAX_LENGTH])
int helpFunc (char parameters[][MAX_LENGTH])
helpFunc calls the other help functions
void help ()
help prints out a list of all possible commands and a brief description of what they do.
int helpGetVersion ()
helpGetVersion prints the help instructions for version. Tells the user what the command and arguments for 'version' are.
void helpGetDate ()
helpGetDate prints the help instructions for get date. Tells the user what the command and arguments for 'get date' are.
void helpSetDate ()
helpSetDate prints the help instructions for set date. Tells the user what the command and arguments for 'set date' are.
void helpGetTime ()
helpGetTime prints the help instructions for get time. Tells the user what the commands and arguments for 'get time' are.
void helpSetTime ()
helpSetTime prints the help instructions for set time. Tells the user what the command and arguments for 'set time' are.
void helpShutdown ()
helpShutdown prints the help instructions for set date. Tells the user what the command and arguments for 'set date' are.
void helpVersion ()
helpVersion prints the help instructions for using the version command. No arguments are required.
void helpDate (char parameters[][MAX_LENGTH])
helpDate prints out the help information for date, for date –set and date –get
void helpTime (char parameters[][MAX_LENGTH])
helpTime prints out the help information for time, for time –set and time –get
void helpPcb (char parameters[][MAX_LENGTH])
helpPcb takes in the command to print the help information for. Calls the proper function to print the help information for the selected command.
void helpPcbPrint ()
helpPcbPrint prints out the commands for PCBs.
void helpSuspendPCB ()
helpSuspendPCB prints the help instructions for the suspendPCB command.
void helpResumePCB ()
helpResumePCB prints out the parameters and usage of the resume pcb command.
void helpSetPriority ()
helpSetPriority prints out to console the parameters and usage for –setpriority.
void helpShowPCB ()
void helpShowAllProcesses ()
helpShowAllProcesses shows all processes in the system. Takes in no parameters and prints out to the console.
void helpShowReadyProcesses ()
helpShowReadyProcesses shows the parameters and usage for showing ready PCBs.
void helpShowBlockedProcesses ()
helpShowBlockedProcesses shows the parameters and usage for showing the blocked PCBs.
void helpCreatePCB ()
helpCreatePCB prints out the parameters and usage for createPCB.
void helpDeletePCB ()
helpDeletePCB prints out the parameters and usage for deleting a PCB.
void helpBlockPCB ()
helpBlockPCB prints out the parameters and usage for blocking a PCB.
void helpUnblockPCB ()
helpUnblockPCB prints out the parameters and usage for unblocking a PCB.
int version (char parameters[][MAX_LENGTH])
version prints out the current version of the operating system. It will print out R1, R2, R3, ... depending on the current module.
int date (char parameters[][MAX_LENGTH])
void getDate ()
getDate Get the current date from the system.
void setDate (char parameters[][MAX_LENGTH])
setDate sets the system date using the input from the user.
int time (char parameters[][MAX_LENGTH])
void getTime ()
getTime this function has the side-effect of printing the current time to the terminal.
void setTime (char parameters[][MAX_LENGTH])
setTime sets the current system time from the users input.
int shutdownFunc (char parameters[][MAX_LENGTH])
shutdownFunc shuts down the OS.
int pcbFunc (char parameters[][MAX_LENGTH])
int suspendPCB (char parameters[][MAX_LENGTH])
suspendPCB suspends the pcb passed in by the user
int resumePCB (char parameters[][MAX_LENGTH])
resumePCB resumes the PCB passed in by the user
int setPriority (char *procName, char *procPrio)
setPriority sets the priority of a particular process
int showPCB (char parameters[][MAX_LENGTH])
showPCB shows the process information for the process requested by the user
int showAllProcesses (char parameters[][MAX_LENGTH])
showAllProcesses shows all processes in the system.
int showReadyProcesses (char parameters[][MAX_LENGTH])
showReadyProcesses shows all processes that are ready, in the ready queue (linked list).
int showBlockedProcesses (char parameters[][MAX_LENGTH])
showBlockedProcesses shows all processes that are blocked.
int createPCB (const char *pcbName, const char *pcbPriority, const char *pcbClass)
createPCB creates a new PCB and allocates memory for the PCB.
int deletePCB (char parameters[][MAX_LENGTH])
deletePCB deletes the PCB requested by the user.
int blockPCB (char parameters[][MAX_LENGTH])
blockPCB blocks the specified PCB
int unblockPCB (char parameters[][MAX_LENGTH])
unblockPCB unblocks the specified PCB.
int yield (char parameters[][MAX_LENGTH])
stops the exection of commhand and executes each process in the ready queue
int loadr3 (char parameters[][MAX_LENGTH])
loads all processes into memory in a suspended ready state at any priority of the users choosing
void initCmdArray (cmd_struct_t *arr)
Variables
struct s_cmd_struct __attribute__
cmd_struct_t cmdArray [MAX_CMD_LIST_LENGTH]
Macro Definition Documentation
#define MAX_CMD_LIST_LENGTH 50
Definition at line 6 of file comm_list.h.
Referenced by exec_comm().
Typedef Documentation
typedef struct s_cmd_struct cmd_struct_t
Definition at line 8 of file comm_list.h.
Function Documentation
int blockPCB (char parameters[][MAX_LENGTH])
blockPCB blocks the specified PCB
Parameters
parameters takes in the name of the PCB to move to the blocked queue.
Returns
an integer, normally 0.
Definition at line 704 of file comm_list.c.
References BLOCKED, changeProcessState(), errorToString(), printf, showPCB(), and SUCCESS.
Referenced by pcbFunc().
{
     e_PCB_ERROR_CODE_t retVal = changeProcessState((const char*)parameters[0], BLOCKED);
     if(retVal == SUCCESS)
     {
         showPCB(parameters);
     }
     printf("Status: %s\r\n", errorToString(retVal));
     return retVal;
 //    const char* name = (const char*)parameters[0];
 //    changeProcessState(name, BLOCKED);
 //    return 0;
 }
int createPCB (const char * pcbName, const char * pcbPriority, const char * pcbClass)
createPCB creates a new PCB and allocates memory for the PCB.
Parameters
pcbName the name of the PCB to be created
pcbPriority the priority of the PCB to be created
pcbClass the class of the PCB to be created
Returns
an integer, normally 0.
Definition at line 683 of file comm_list.c.
References atoi(), errorToString(), prevPCBError, printf, setupPCB(), and stringToClass().
Referenced by pcbFunc().
{
     setupPCB(pcbName, stringToClass(pcbClass), atoi(pcbPriority));
     //printf("Clas String %s: num %d\r\n", pcbClass, (int) stringToClass(pcbClass));
     printf("Status: %s\r\n", errorToString(prevPCBError));
     return prevPCBError;
 }
int date (char parameters[][MAX_LENGTH])
Definition at line 350 of file comm_list.c.
References getDate(), serial_println(), setDate(), and strcmp().
Referenced by initCmdArray().
{
     if(!strcmp(parameters[0],"--get")) {
         getDate();
     } else if(!strcmp(parameters[0],"--set")) {
         setDate(&parameters[1]);
     } else {
         serial_println("Check your input, there are only 12 months in a year.");
     }
     return 0;
 }
int deletePCB (char parameters[][MAX_LENGTH])
deletePCB deletes the PCB requested by the user.
Parameters
parameters takes in the name of the PCB to be deleted.
Returns
an integer, normally 0.
Definition at line 692 of file comm_list.c.
References errorToString(), findPCB(), freePCB(), prevPCBError, and printf.
Referenced by pcbFunc().
{
     pcb_t* foundPCB = findPCB((const char*)parameters[0]);
     if(!foundPCB)
     {
         printf("Status: %s\r\n", errorToString(prevPCBError));
         return prevPCBError;
     }
     e_PCB_ERROR_CODE_t retval = freePCB(foundPCB);
     printf("Status: %s\r\n", errorToString(retval));
     return retval;
 }
void getDate ()
getDate Get the current date from the system.
No parameters required, prints out a date.
Definition at line 361 of file comm_list.c.
References get_date(), and printf.
Referenced by date(), and setDate().
                {
     int month=0, day=0, year=0;
     get_date(&day, &month, &year);
     printf("The current date is %d/%d/20%d UTC\r\n", day, month, year);
 }
int getNumDaysInMonth (int month, int year)
getNumDaysInMonth is a helper function to allow the easy retrieval of days in a month based on the month input by the user.
Parameters
month is an integer from 1-12
year is an integer representing the year to check if it's a leap year
Returns
the number of days in the corresponding month
Definition at line 14 of file comm_list.c.
Referenced by setDate().
{
     int days = 0;
     switch (month) {
     case 01: case 3: case 5: case 7: case 8: case 10: case 12:
         days = 31;
         break;
     case 4: case 6: case 9: case 11:
         days = 30;
         break;
     case 2:
         if(year%4==0)
             days = 29;
         else
             days = 28;
     default:
         break;
     }
     return days;
 }
void getTime ()
getTime this function has the side-effect of printing the current time to the terminal.
No parameters are required.
Definition at line 404 of file comm_list.c.
References get_time(), serial_print(), and sprintf().
Referenced by setTime(), and time().
                {
     int hour=0, minutes=0, seconds=0;
     get_time(&hour, &minutes, &seconds);
     char buf[500]; \
     sprintf(buf, 500, "\033[38;2;255;0;255mThe current time is %d:%d.%d UTC\r\n\033[38;2;255;255;255m", hour, minutes, seconds); \
     serial_print(buf);
     //printf("\033[38;2;255;0;255mThe current time is %d:%d.%d UTC\r\n\033[38;2;255;255;255m", hour, minutes, seconds);
 }
void help ()
help prints out a list of all possible commands and a brief description of what they do.
Definition at line 67 of file comm_list.c.
References BG_BLACK, BG_DARK_RED, BG_WHITE, COLOR_BLACK, COLOR_BLUE, COLOR_GREEN, COLOR_MAGENTA, COLOR_ORANGE, COLOR_RED, COLOR_STOP, COLOR_WHITE, COLOR_YELLOW, helpPcbPrint(), printf, and serial_println().
Referenced by helpFunc().
             {
     printf("%s%sUNIX style commands%s\r\n",COLOR_BLACK, BG_WHITE, COLOR_STOP);
     printf("%s%sCommand   | what it does%s\r\n", COLOR_BLACK, BG_WHITE, COLOR_STOP);
     printf("%s%s-------   | -----------------------------------%s\r\n", COLOR_WHITE, BG_DARK_RED, COLOR_STOP);
     printf("%s%sdate      | Interact with the current system date%s\r\n",COLOR_RED, BG_BLACK, COLOR_STOP);
     printf("%s%shelp      | Shows the command options%s\r\n", COLOR_ORANGE, BG_WHITE, COLOR_STOP);
     printf("%s%spcb       | Work with the processes%s\r\n", COLOR_YELLOW, BG_DARK_RED, COLOR_STOP);
     printf("%s%sshutdown  | Shut down the system%s\r\n", COLOR_GREEN, BG_BLACK, COLOR_STOP);
     printf("%s%stime      | Interact with the current system time%s\r\n", COLOR_BLUE, BG_WHITE, COLOR_STOP);
     printf("%s%sversion   | Get the current version of the OS%s\r\n", COLOR_MAGENTA, BG_DARK_RED, COLOR_STOP);
     serial_println(" ");
     helpPcbPrint();
     printf("%sScroll up for additional commands%s\r\n", COLOR_RED, COLOR_STOP);
 }
void helpBlockPCB ()
helpBlockPCB prints out the parameters and usage for blocking a PCB.
Definition at line 321 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                     {
     serial_println("Removes the PCB from current queue and places it into the blocked queue.");
     serial_println("Command: pcb --block");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of the PCB'");
     serial_println(" ");
 }
void helpCreatePCB ()
helpCreatePCB prints out the parameters and usage for createPCB.
Definition at line 305 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                      {
     serial_println("Creates a new PCB and allocates memory.");
     serial_println("Command: pcb --create");
     serial_println("Arguments:");
     serial_println("-n/--name 'the name of the PCB'\n-p/--priority 'priority from 0-9 of pcb'\n-c/--class 'System or User_app'");
     serial_println(" ");
 }
void helpDate (char parameters[][MAX_LENGTH])
helpDate prints out the help information for date, for date –set and date –get
Parameters
parameters takes in a char array
[0] can be –set or –get or empty –set tells the parameters and usage for setting the date –get tells the parameters and usage for getting the date
Definition at line 152 of file comm_list.c.
References serial_println(), strcmp(), and strlen().
Referenced by helpFunc().
 {
     if(!strlen(parameters[0]))
     {
         serial_println("Retireves or Sets the system date");
         serial_println("Command: 'date'");
         serial_println("\033[38;2;255;255;0mArguments available: \033[38;2;255;0;0m--set, --get\033[0m");
         serial_println("Enter the command 'help date --get' or 'help date --set'");
     }
     else if(!strcmp(parameters[0], "--set"))
     {
         serial_println("Sets the system date");
         serial_println("Command: 'date --set'");
         serial_println("Usage: \033[38;2;255;255;0m 'date --set' \"DD/MM/YYYY\" \033[0m");
     }
     else if(!strcmp(parameters[0], "--get"))
     {
         serial_println("Gets the system date");
         serial_println("Command: 'date --get'");
         serial_println("Usage: \033[38;2;255;255;0m 'date --get' \033[0m");
     }
 }
void helpDeletePCB ()
helpDeletePCB prints out the parameters and usage for deleting a PCB.
Definition at line 313 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                      {
     serial_println("Delete the specified PCB and frees memory.  Removes the PCB from any queues it is currently in.");
     serial_println("Command: pcb --delete");
     serial_println("Arguments:");
     serial_println("-n/--name 'the name of the PCB'");
     serial_println(" ");
 }
int helpFunc (char parameters[][MAX_LENGTH])
helpFunc calls the other help functions
Parameters
parameters used to determine if just help or help set date was called
Returns
an integer.
Definition at line 48 of file comm_list.c.
References help(), helpDate(), helpGetVersion(), helpPcb(), helpShutdown(), helpTime(), IMPROPER_COMMAND, serial_println(), and strcmp().
Referenced by initCmdArray().
{
     if(!strcmp(parameters[0],"") || !strcmp(parameters[0],"\0")) {
         help();
     } else if(strcmp(parameters[0],"shutdown")==0) {
         helpShutdown();
     } else if(strcmp(parameters[0],"version")==0) {
         helpGetVersion();
     } else if(strcmp(parameters[0],"time")==0) {
         helpTime(&parameters[1]);
     } else if(strcmp(parameters[0],"date")==0) {
         helpDate(&parameters[1]);
     } else if(strcmp(parameters[0], "pcb")==0) {
         helpPcb(&parameters[1]);
     } else {
         serial_println(IMPROPER_COMMAND);
     }
     return 0;
 }
void helpGetDate ()
helpGetDate prints the help instructions for get date. Tells the user what the command and arguments for 'get date' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 94 of file comm_list.c.
References serial_println().
                    {
     serial_println("Get the current date.");
     serial_println("Command: 'get date'");
     serial_println("There are no arguments required.");
     serial_println(" ");
 }
void helpGetTime ()
helpGetTime prints the help instructions for get time. Tells the user what the commands and arguments for 'get time' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 110 of file comm_list.c.
References serial_println().
                    {
     serial_println("Get the current time in UTC.");
     serial_println("Command: 'get time'");
     serial_println("There are no arguments required.");
     serial_println(" ");
 }
int helpGetVersion ()
helpGetVersion prints the help instructions for version. Tells the user what the command and arguments for 'version' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 85 of file comm_list.c.
References COLOR_RED, COLOR_STOP, COLOR_YELLOW, and printf.
Referenced by helpFunc().
                      {
     printf("%sGet the current version of the operating system%s\r\n",COLOR_RED, COLOR_STOP);
     printf("Command: '%sversion%s'\r\n",COLOR_YELLOW,COLOR_STOP);
     printf("%sThere are no arguments required.\r\n","");
     printf("%sThis will return R1, R2,... showing the current module.\r\n","");
     printf("%s\r\n","");
     return 0;
 }
void helpPcb (char parameters[][MAX_LENGTH])
helpPcb takes in the command to print the help information for. Calls the proper function to print the help information for the selected command.
Parameters
parameters takes in a character array
Definition at line 198 of file comm_list.c.
References helpBlockPCB(), helpCreatePCB(), helpDeletePCB(), helpPcbPrint(), helpResumePCB(), helpSetPriority(), helpShowAllProcesses(), helpShowBlockedProcesses(), helpShowPCB(), helpShowReadyProcesses(), helpSuspendPCB(), helpUnblockPCB(), isEmpty(), serial_println(), and strcmp().
Referenced by helpFunc().
{
     if(isEmpty(&parameters[0])) {
         helpPcbPrint();
     } else if(!strcmp(parameters[0],"--block")) {
         helpBlockPCB();
     } else if(!strcmp(parameters[0],"--create")) {
         helpCreatePCB();
     } else if(!strcmp(parameters[0], "--delete")) {
         helpDeletePCB();
     } else if(!strcmp(parameters[0], "--resume")) {
         helpResumePCB();
     } else if(!strcmp(parameters[0], "--setpriority")) {
         helpSetPriority();
     } else if(!strcmp(parameters[0], "--show")) {
         helpShowPCB();
     } else if(!strcmp(parameters[0],"--showall")) {
         helpShowAllProcesses();
     } else if(!strcmp(parameters[0], "--showblocked")) {
         helpShowBlockedProcesses();
     } else if(!strcmp(parameters[0], "--showready")) {
         helpShowReadyProcesses();
     } else if(!strcmp(parameters[0], "--suspend")) {
         helpSuspendPCB();
     } else if(!strcmp(parameters[0],"--unblock")) {
         helpUnblockPCB();
     } else {
         serial_println("Invalid parameter, run 'help pcb' to see the valid parameters.");
     }
 }
void helpPcbPrint ()
helpPcbPrint prints out the commands for PCBs.
Definition at line 228 of file comm_list.c.
References serial_println().
Referenced by help(), and helpPcb().
                     {
     serial_println("PCB commands\r\n");
     serial_println("Use 'pcb [command]'");
     serial_println("   Command    | what it does");
     serial_println("____________  | _________________________________");
     serial_println("--block       | Sends the PCB to the blocked queue");
     serial_println("--create      | Creates a new PCB and allocates memory");
     serial_println("--delete      | Delete specified PCB and frees memory");
     serial_println("--resume      | Resume the specified PCB");
     serial_println("--setpriority | Set/change the priority of the specified PCB");
     serial_println("--show        | Show the specified PCB");
     serial_println("--showall     | Show all of the PCBs");
     serial_println("--showblocked | Show the PCBs in the blocked queue");
     serial_println("--showready   | Show the PCBs in the ready queue");
     serial_println("--suspend     | Suspends the specified PCB");
     serial_println("--unblock     | Moves the specified PCB from the blocked state to ready queue");
     serial_println(" ");
     serial_println("Type 'help [command]' to see what the command does and arguments it requires.");
     serial_println(" ");
 }
void helpResumePCB ()
helpResumePCB prints out the parameters and usage of the resume pcb command.
Definition at line 257 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                      {
     serial_println("Resume the specified PCB.  Removes PCB from suspended queue and places it into the appropriate queue.");
     serial_println("Command: pcb --resume");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of the PCB'");
     serial_println(" ");
 }
void helpSetDate ()
helpSetDate prints the help instructions for set date. Tells the user what the command and arguments for 'set date' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 101 of file comm_list.c.
References serial_println().
                    {
     serial_println("Set the current date");
     serial_println("Command: 'set date --set \"DD/MM/YYYY\" ");
     serial_println("Arguments:");
     serial_println("--set \"MM/DD/YYYY\"");
     serial_println("ex. 'set date --set \"03/12/2017\"'");
     serial_println(" ");
 }
void helpSetPriority ()
helpSetPriority prints out to console the parameters and usage for –setpriority.
Definition at line 265 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
{
     serial_println("Set/change the priority of a particular PCB.");
     serial_println("Command: pcb --setpriority");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of PCB'\n-p/--priority 'priority from 0-9'");
     serial_println(" ");
 }
void helpSetTime ()
helpSetTime prints the help instructions for set time. Tells the user what the command and arguments for 'set time' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 117 of file comm_list.c.
References serial_println().
                   {
     serial_println("Set the current time in UTC");
     serial_println("Command: 'set time --set \"HH:MM.SS\"'");
     serial_println("Arguments: ");
     serial_println("--set \"HH:MM.SS\"   using 24 hour");
     serial_println("ex. 'set time --set[14:20.00]' to set the system time to 2:20.00 PM");
     serial_println(" ");
 }
void helpShowAllProcesses ()
helpShowAllProcesses shows all processes in the system. Takes in no parameters and prints out to the console.
Definition at line 281 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
{
     serial_println("Show all of the processes in the system.");
     serial_println("Command: pcb --showall");
     serial_println("Arguments:");
     serial_println("No arguments required.");
     serial_println(" ");
 }
void helpShowBlockedProcesses ()
helpShowBlockedProcesses shows the parameters and usage for showing the blocked PCBs.
Definition at line 297 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
{
     serial_println("Show all of the processes that are in the blocked queue.");
     serial_println("Command: pcb --showblocked");
     serial_println("Arguments:");
     serial_println("No arguments required.");
     serial_println(" ");
 }
void helpShowPCB ()
Definition at line 273 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                    {
     serial_println("Show the information for a particular PCB.");
     serial_println("Command: pcb --show");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of the PCB'");
     serial_println(" ");
 }
void helpShowReadyProcesses ()
helpShowReadyProcesses shows the parameters and usage for showing ready PCBs.
Definition at line 289 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
{
     serial_println("Show all of the processes that are in the ready queue.");
     serial_println("Command: pcb --showready");
     serial_println("Arguments:");
     serial_println("No arguments required.");
     serial_println(" ");
 }
void helpShutdown ()
helpShutdown prints the help instructions for set date. Tells the user what the command and arguments for 'set date' are.
No parameters are needed to be passed in, as it just prints to the console.
Definition at line 126 of file comm_list.c.
References COLOR_BLACK, COLOR_BLUE, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, COLOR_ORANGE, COLOR_PINK, COLOR_RED, COLOR_RED_DARK, COLOR_STOP, COLOR_YELLOW, printf, and serial_println().
Referenced by helpFunc().
                     {
     printf("%sShut down the system%s\r\n",COLOR_RED, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_BLUE, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_GREEN, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_BLACK, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_CYAN, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_MAGENTA, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_YELLOW, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_ORANGE, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_PINK, COLOR_STOP);
     printf("%sShut down the system%s\r\n",COLOR_RED_DARK, COLOR_STOP);
     serial_println("Shut down the system.");
     serial_println("Command: 'shutdown'");
     serial_println("No arguments required.");
     serial_println("You will be prompted to confirm that you want to shutdown.");
     serial_println(" ");
 }
void helpSuspendPCB ()
helpSuspendPCB prints the help instructions for the suspendPCB command.
Definition at line 249 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                       {
     serial_println("Suspend a particular PCB.");
     serial_println("Command: pcb --suspend");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of the pcb");
     serial_println(" ");
 }
void helpTime (char parameters[][MAX_LENGTH])
helpTime prints out the help information for time, for time –set and time –get
Parameters
parameters takes in a char array
[0] can be –set or –get or empty –set tells the parameters and usage for setting the time –get tells the parameters and usage for getting the time
Definition at line 175 of file comm_list.c.
References serial_println(), strcmp(), and strlen().
Referenced by helpFunc().
 {
     if(!strlen(parameters[0]))
     {
         serial_println("Retrieves or Sets the system time");
         serial_println("Command: 'time'");
         serial_println("\033[38;2;255;255;0mArguments available: \033[38;2;255;0;0m--set, --get\033[0m");
         serial_println("Enter the command 'help time --get' or 'help time --set'");
     }
     else if(!strcmp(parameters[0], "--set"))
     {
         serial_println("Sets the system time");
         serial_println("Command: 'time --set'");
         serial_println("Usage: \033[38;2;255;255;0m 'time --set' \"HH:MM.SS\" \033[0m");
     }
     else if(!strcmp(parameters[0], "--get"))
     {
         serial_println("Gets the system date");
         serial_println("Command: 'time --get'");
         serial_println("Usage: \033[38;2;255;255;0m 'time --get' \033[0m");
     }
 }
void helpUnblockPCB ()
helpUnblockPCB prints out the parameters and usage for unblocking a PCB.
Definition at line 329 of file comm_list.c.
References serial_println().
Referenced by helpPcb().
                       {
     serial_println("Removes the PCB from the blocked queue and places it into the ready queue.");
     serial_println("Command: pcb --unblock");
     serial_println("Arguments:");
     serial_println("-n/--name 'name of the PCB'");
     serial_println(" ");
 }
void helpVersion ()
helpVersion prints the help instructions for using the version command. No arguments are required.
Definition at line 145 of file comm_list.c.
References serial_println().
                    {
     serial_println("Shows the version of the operating system.");
     serial_println("Command: 'version'");
     serial_println("No arguments required.");
     serial_println("\r\n");
 }
void initCmdArray (cmd_struct_t * arr)
Definition at line 172 of file commhand.c.
References s_cmd_struct::cmdFunc, s_cmd_struct::cmdName, date(), helpFunc(), loadr3(), pcbFunc(), shutdownFunc(), time(), version(), and yield().
Referenced by init_commhand().
{
     arr[0].cmdName = "help";
     arr[0].cmdFunc = &helpFunc;
     arr[1].cmdName = "version";
     arr[1].cmdFunc = &version;
     arr[2].cmdName = "date";
     arr[2].cmdFunc = &date;
     arr[3].cmdName = "time";
     arr[3].cmdFunc = &time;
     arr[4].cmdName = "shutdown";
     arr[4].cmdFunc = &shutdownFunc;
     arr[5].cmdName = "pcb";
     arr[5].cmdFunc = &pcbFunc;
     arr[6].cmdName = "yield";
     arr[6].cmdFunc = &yield;
     arr[7].cmdName = "loadr3";
     arr[7].cmdFunc = &loadr3;
 }
int isEmpty (char parameters[][MAX_LENGTH])
Definition at line 34 of file comm_list.c.
References strcmp().
Referenced by helpPcb(), and pcbFunc().
{
     int empty = 0;
     if((!strcmp(parameters[0],"")) || (!strcmp(parameters[0],"\0"))) {
         empty = 1;
     }
     return empty;
 }
int pcbFunc (char parameters[][MAX_LENGTH])
Definition at line 468 of file comm_list.c.
References blockPCB(), createPCB(), deletePCB(), EXTRA_PARAMETERS, isEmpty(), printf, resumePCB(), serial_print(), serial_println(), setPriority(), showAllProcesses(), showBlockedProcesses(), showPCB(), showReadyProcesses(), strcmp(), suspendPCB(), and unblockPCB().
Referenced by initCmdArray().
{
     if(!strcmp(parameters[0],"--suspend")) {
         if(isEmpty(&parameters[1])) {
             serial_println("Missing name of PCB to suspend.");
         } else {
             if(!isEmpty(&parameters[2]) &&
                     (!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name"))) {
                 suspendPCB(&parameters[2]);
             } else {
                 suspendPCB((&parameters[2]));
                 serial_print(EXTRA_PARAMETERS);
                 serial_print(parameters[3]);
                 serial_print("\r\n");
             }
         }
     } else if(!strcmp(parameters[0],"--resume")) {
         if(isEmpty(&parameters[1])) {
             serial_println("Missing name of PCB to suspend.");
         } else {
             if(!isEmpty(&parameters[2]) &&
                     (!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name"))) {
                 resumePCB(&parameters[2]);
             } else {
                 resumePCB((&parameters[2]));
                 serial_print(EXTRA_PARAMETERS);
                 serial_print(parameters[3]);
                 serial_print("\r\n");            }
         }
     } else if(!strcmp(parameters[0],"--setpriority")) {
         if(isEmpty(&parameters[4])) {
             serial_println("Missing parameters.");
         } else {
             if((!strcmp(parameters[1],"--name") || !strcmp(parameters[1],"-n")) && (!strcmp(parameters[3],"--priority") || !strcmp(parameters[3],"-p"))) {
                 setPriority(parameters[2], parameters[4]);
             } else if((!strcmp(parameters[3],"--name") || !strcmp(parameters[3],"-n")) && (!strcmp(parameters[1],"--priority") || !strcmp(parameters[1],"-p"))) {
                 setPriority(parameters[4], parameters[2]);
             } else {
                 printf("%sProper command: 'pcb --setpriority -n \"pcb name\" -p \"pcb priority\"","");
             }
         }
     } else if(!strcmp(parameters[0],"--show")) {
         if(isEmpty(&parameters[2])) {
             printf("Missing name of pcb to show%s.\n","");
         } else {
             if(!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name")) {
                 showPCB(&parameters[2]);
             } else {
                 printf("Type 'help pcb --show' to see the arguments required.%s\n","");
             }
         }
     } else if(!strcmp(parameters[0],"--showall")) {
         if(isEmpty(&parameters[1])) {
             showAllProcesses(&parameters[0]);
         } else {
             printf("No arguments required%s\n","");
             showAllProcesses(&parameters[0]);
         }
     } else if(!strcmp(parameters[0],"--showready")) {
         if(isEmpty(&parameters[1])) {
             showReadyProcesses(&parameters[0]);
         } else {
             printf("No arguments required%s\n","");
             showReadyProcesses(&parameters[0]);
         }
     } else if(!strcmp(parameters[0],"--showblocked")) {
         if(isEmpty(&parameters[1])) {
             showBlockedProcesses(&parameters[0]);
         } else {
             printf("No arguments required%s\n","");
             showBlockedProcesses(&parameters[0]);
         }
     } else if(!strcmp(parameters[0],"--create")) {
         if(isEmpty(&parameters[6])) {
             printf("Missing parameters of pcb to create%s.\n","");
         } else {
             char * procName; char * procPrio; char * procClass;
             int i = 0;
             for(;!isEmpty(&parameters[i]); i++) {
                 if(!strcmp(parameters[i], "--name") || !strcmp(parameters[i],"-n")) {
                     i++;
                     procName = parameters[i];
                 } else if(!strcmp(parameters[i], "--priority") || !strcmp(parameters[i],"-p")) {
                     i++;
                     procPrio = parameters[i];
                 } else if(!strcmp(parameters[i], "--class") || !strcmp(parameters[i],"-c")) {
                     i++;
                     procClass = parameters[i];
                 }
             }
             createPCB(procName, procPrio, procClass);
         }
     } else if(!strcmp(parameters[0],"--delete")) {
         if(isEmpty(&parameters[2])) {
             printf("Missing name of pcb to create%s.\n","");
         } else {
             if(!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name")) {
                 deletePCB(&parameters[2]);
             } else {
                 printf("Type 'help pcb --delete' to see the arguments required.%s\n","");
             }
         }
     } else if(!strcmp(parameters[0],"--block")) {
         if(isEmpty(&parameters[2])) {
             printf("Missing name of pcb to create%s.\n","");
         } else {
             if(!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name")) {
                 blockPCB(&parameters[2]);
             } else {
                 printf("Type 'help pcb --block' to see the arguments required.%s\n","");
             }
         }
     } else if(!strcmp(parameters[0],"--unblock")) {
         if(isEmpty(&parameters[2])) {
             printf("Missing name of pcb to create%s.\n","");
         } else {
             if(!strcmp(parameters[1],"-n") || !strcmp(parameters[1],"--name")) {
                 unblockPCB(&parameters[2]);
             } else {
                 printf("Type 'help pcb --unblock' to see the arguments required.%s\n","");
             }
         }
     }
     return 0;
 }
int resumePCB (char parameters[][MAX_LENGTH])
resumePCB resumes the PCB passed in by the user
Parameters
parameters - the rest of the input from the user, the name of the PCB to be resumed.
Returns
an integer, normally 0.
Definition at line 619 of file comm_list.c.
References changeProcessSuspensionState(), errorToString(), NOT_SUSPENDED, printf, showPCB(), and SUCCESS.
Referenced by pcbFunc().
{
     e_PCB_ERROR_CODE_t retVal = changeProcessSuspensionState((const char*)parameters[0], NOT_SUSPENDED);
     if(retVal == SUCCESS)
     {
         showPCB(parameters);
     }
     printf("Status: %s\r\n", errorToString(retVal));
     return retVal;
 //    const char* name = (const char*)parameters[0];
 //    pcb_t* process = findPCB(name);
 //    e_PROCESS_STATE_t state = process->processState;
 //    if (state == READY)
 //    {
 //        changeProcessState(name, RUNNING);
 //    }
 //    else printf("%s", "\nThe process must be in the ready state to resume.\n");
 //    return 0;
 }
void setDate (char parameters[][MAX_LENGTH])
setDate sets the system date using the input from the user.
Parameters
parameters take the unconsumed parameters from commhandler from the command prompt.
Checks if the parameters exist, otherwise will return improper command. If paramters exist, will check to make sure the parameters are correct, such that the days and months are valid.
Calls set_date from rtc to set the current date. After setting the date, will print the current date.
Ex. Command is "date –set '03/12/2017', 03, 12 , 2017 are passed over. parameters[0] is the day parameters[1] is the month parameters[2] is the year
Definition at line 367 of file comm_list.c.
References atoi(), getDate(), getNumDaysInMonth(), IMPROPER_COMMAND, printf, serial_println(), set_date(), and strlen().
Referenced by date().
{
     //printf("day %d %s, month %d %s, year %d %s\r\n", atoi(parameters[0]), parameters[0], atoi(parameters[1]), parameters[1], atoi(parameters[2]), parameters[2]);
     if(!strlen(parameters[2]) || !atoi(parameters[0]) || !atoi(parameters[1]) || !atoi(parameters[2]))
     {
         serial_println(IMPROPER_COMMAND);
         serial_println("\r\nInvalid Parameters");
     }
     else
     {
         int daysInMonth = getNumDaysInMonth(atoi(parameters[1]), atoi(parameters[2]));
         if((atoi(parameters[0]) > 0) && (daysInMonth >= atoi(parameters[0]))){
             set_date(atoi(parameters[0]), atoi(parameters[1]), atoi(parameters[2]));
         } else {
             serial_println("Double check the input parameters");
             printf("\033[38;2;255;0;255mTotal days in your selected month are:  %d UTC\r\n\033[38;2;255;255;255m", daysInMonth);
             serial_println("\r\n");
         }
     }
     getDate();
 }
int setPriority (char * procName, char * procPrio)
setPriority sets the priority of a particular process
Parameters
procName is the process name to be modified
procPrio is the new priority of the PCB
Returns
an integer, normally 0 procPrio is the process procName is the priority
Definition at line 640 of file comm_list.c.
References atoi(), changeProcessPriority(), errorToString(), findPCB(), printf, and printPCBFunc().
Referenced by pcbFunc().
{
     //serial_println("PRINTING OUT");
     printf("Status: %s\r\n", errorToString(changeProcessPriority(procName, atoi(procPrio))));
     printPCBFunc((void*)findPCB(procName));
     return 0;
 }
void setTime (char parameters[][MAX_LENGTH])
setTime sets the current system time from the users input.
Parameters
parameters take the unconsumed parameters from commhandler from the command prompt.
Calls set_time from rtc to set the sytem time. Then prints out the current time.
Ex. Command is "time –set '14:20.55', 14, 20 , 55 are passed over. parameters[1] is the hour (24 hour) parameters[2] is the minute parameters[3] is the second
Definition at line 414 of file comm_list.c.
References atoi(), getTime(), IMPROPER_COMMAND, serial_println(), set_time(), and strlen().
Referenced by time().
{
     if(!strlen(parameters[2]) || !atoi(parameters[0]) || !atoi(parameters[1]) || !atoi(parameters[2]))
     {
         serial_println(IMPROPER_COMMAND);
         serial_println("\r\nInvalid Parameters");
     }
     else
     {
         if(atoi(parameters[0]) < 0 || atoi(parameters[0]) > 24 || atoi(parameters[1]) < 0 || atoi(parameters[1]) > 59 || atoi(parameters[2]) < 0 || atoi(parameters[2]) > 59) {
             serial_println("Double check the input parameters");
             serial_println("Make sure 0 HH 24 and 0 MM 59 and 0 SS 59");
             serial_println("\r\n");
         } else {
             set_time(atoi(parameters[0]), atoi(parameters[1]), atoi(parameters[2]));
         }
     }
     getTime();
 }
int showAllProcesses (char parameters[][MAX_LENGTH])
showAllProcesses shows all processes in the system.
Definition at line 656 of file comm_list.c.
References blockedQueue, printf, printList(), readyQueue, suspendedBlockedQueue, and suspendedReadyQueue.
Referenced by pcbFunc().
{
     (void)parameters;
     printf("\n\nReady Queue:%s","\r\n");
     printList(&readyQueue);
     printf("\n\nBlocked Queue:%s","\r\n");
     printList(&blockedQueue);
     printf("\n\nSuspended-Ready Queue:%s","\r\n");
     printList(&suspendedReadyQueue);
     printf("\n\nSuspended-Blocked Queue:%s","\r\n");
     printList(&suspendedBlockedQueue);
     return 0;
 }
int showBlockedProcesses (char parameters[][MAX_LENGTH])
showBlockedProcesses shows all processes that are blocked.
Returns
an integer, normally 0.
Definition at line 676 of file comm_list.c.
References blockedQueue, printf, and printList().
Referenced by pcbFunc().
{
     (void)parameters;
     printf("%s", "\n\nBlocked Queue:\n");
     printList(&blockedQueue);
     return 0;
 }
int showPCB (char parameters[][MAX_LENGTH])
showPCB shows the process information for the process requested by the user
Parameters
parameters the name of the PCB to show the information of.
Definition at line 647 of file comm_list.c.
References errorToString(), findPCB(), prevPCBError, printf, and printPCBFunc().
Referenced by blockPCB(), pcbFunc(), resumePCB(), suspendPCB(), and unblockPCB().
{
     pcb_t* process = findPCB((const char*)parameters[0]);
     if(!process) { printf("Status: %s\r\n", errorToString(prevPCBError)); return prevPCBError; }
     printPCBFunc((void*)process);
     return prevPCBError;
 }
int showReadyProcesses (char parameters[][MAX_LENGTH])
showReadyProcesses shows all processes that are ready, in the ready queue (linked list).
Definition at line 669 of file comm_list.c.
References printf, printList(), and readyQueue.
Referenced by pcbFunc().
{
     (void)parameters;
     printf("%s", "\n\nReady Queue:\n");
     printList(&readyQueue);
     return 0;
 }
int shutdownFunc (char parameters[][MAX_LENGTH])
shutdownFunc shuts down the OS.
Parameters
parameters the input from the user
Returns
an integer, if the user confirms to shutdown will return 9, otherwise will return 0.
Definition at line 435 of file comm_list.c.
References in_string, MAX_LENGTH, serial_poll(), serial_print(), serial_println(), sprintf(), and strcmp().
Referenced by initCmdArray().
{
     int retVal = 0;
     char buf[500]; \
     sprintf(buf, 500, "\033[38;2;255;0;255mShutdown called\r\n\033[38;2;255;255;255m"); \
     serial_println("Shutdown was called.\r\n");
     if(strcmp(parameters[1],"")==0) {
         int confirm = 0;
         char in_string[MAX_LENGTH];
         serial_print("Confirm shutdown y/n?: ");
         if(confirm == 0) {
             serial_print("");
             serial_poll(in_string);
             if(strcmp(in_string, "y")==0)
                 confirm = 1;
             else if (strcmp(in_string, "n")==0)
                 confirm = 2;
         }
         serial_println(" ");
         if(confirm == 1)
             retVal = 9;
     } else {
         serial_println("UNKNOWN_COMMAND");
     }
     return retVal;
 }
int suspendPCB (char parameters[][MAX_LENGTH])
suspendPCB suspends the pcb passed in by the user
Parameters
parameters takes in the name of the PCB to be suspended.
Returns
an integer, normally 0.
Definition at line 598 of file comm_list.c.
References changeProcessSuspensionState(), errorToString(), printf, showPCB(), SUCCESS, and SUSPENDED.
Referenced by pcbFunc().
{
     e_PCB_ERROR_CODE_t retVal = changeProcessSuspensionState((const char*)parameters[0], SUSPENDED);
     if(retVal == SUCCESS)
     {
         showPCB(parameters);
     }
     printf("Status: %s\r\n", errorToString(retVal));
     return retVal;
 //    const char* name = (const char*)parameters[0];
 //    pcb_t* process = findPCB(name);
 //    e_PROCESS_STATE_t state = process->processState;
 //    if (state == READY || state == RUNNING)
 //    {
 //        changeProcessState(name, BLOCKED);
 //    }
 //    else printf("%s", "\nThe process needs to either be in the ready or the running state to suspend.\n");
 //    return 0;
 }
int time (char parameters[][MAX_LENGTH])
Definition at line 393 of file comm_list.c.
References getTime(), serial_println(), setTime(), and strcmp().
Referenced by initCmdArray().
{
     if(!strcmp(parameters[0],"--get")) {
         getTime();
     } else if(!strcmp(parameters[0],"--set")) {
         setTime(&parameters[1]);
     } else {
         serial_println("ERROR HAS BEEN NOTICED");
     }
     return 0;
 }
int unblockPCB (char parameters[][MAX_LENGTH])
unblockPCB unblocks the specified PCB.
Parameters
parameters takes in the name of the PCB to move from the blocked queue to the ready queue.
Definition at line 717 of file comm_list.c.
References changeProcessState(), errorToString(), printf, READY, showPCB(), and SUCCESS.
Referenced by pcbFunc().
{
     e_PCB_ERROR_CODE_t retVal = changeProcessState((const char*)parameters[0], READY);
     if(retVal == SUCCESS)
     {
         showPCB(parameters);
     }
     printf("Status: %s\r\n", errorToString(retVal));
     return retVal;
 //    const char* name = (const char*)parameters[0];
 //    changeProcessState(name, READY);
 //    return 0;
 }
int version (char parameters[][MAX_LENGTH])
version prints out the current version of the operating system. It will print out R1, R2, R3, ... depending on the current module.
No parameters are required.
Definition at line 339 of file comm_list.c.
References serial_print(), serial_println(), and VERSION.
Referenced by initCmdArray().
{
     (void)parameters;
     serial_print("Version: ");
     serial_print(VERSION);
     serial_println(" ");
     return 0;
 }
Variable Documentation
struct s_cmd_struct __attribute__
cmd_struct_t cmdArray[MAX_CMD_LIST_LENGTH]
Definition at line 13 of file commhand.c.