Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/core/commhand.h File Reference
commhand.h File Reference
Functions
void init_commhand (void)
init_commhand Starts input loop and waits for shutdown code
char * get_hist_up (void)
Function Documentation
char* get_hist_up (void)
Definition at line 162 of file commhand.c.
References comm_hist, and hist_i.
                     {
     hist_i--;
     return comm_hist[hist_i];
 }
void init_commhand (void)
init_commhand Starts input loop and waits for shutdown code
Definition at line 193 of file commhand.c.
References exec_comm(), in_string, initCmdArray(), MAX_LENGTH, PROMPT, serial_poll(), serial_print(), shutdown, and strcpy().
Referenced by kmain().
{
     initCmdArray(cmdArray);
     while(!shutdown) {
         serial_print(PROMPT);
         char in_string[MAX_LENGTH];
         strcpy(in_string, serial_poll(in_string));
         exec_comm(in_string);
     }
 }