Modestus Moon OS: R3
R3
Data Structures
struct context_t
processContext_t structure that conatiains the CPU register context_t
Macros
#define BG_WHITE "\033[48;2;255;255;255m"
Functions
int yield ()
stops the exection of commhand and executes each process in the ready queue
int loadr3 (char parameters[][MAX_LENGTH])
loads all processes into memory in a suspended ready state at any priority of the users choosing
Detailed Description
This grouping provides a quick access to all development that occured during module R2. Each function or file that was added during this module can be found here.
Macro Definition Documentation
#define BG_WHITE "\033[48;2;255;255;255m"
Definition at line 23 of file input.h.
Referenced by help().
Function Documentation
int loadr3 (char parameters[][MAX_LENGTH])
loads all processes into memory in a suspended ready state at any priority of the users choosing
Parameters
parameters tales no parameters so they are voided
Definition at line 825 of file comm_list.c.
References s_processContext::cs, s_processContext::ds, s_processContext::ebp, s_processContext::eflags, s_processContext::eip, s_processContext::es, s_processContext::esp, s_processContext::fs, s_processContext::gs, memset(), proc1(), proc2(), proc3(), proc4(), proc5(), serial_println(), setupPCB(), and SYSTEM.
Referenced by initCmdArray().
{
     (void)parameters;
     serial_println("Loading processes.");
     pcb_t* newPCB = setupPCB("R3-Proc1", SYSTEM, 1);
     processContext_t * cp = ( processContext_t *)( newPCB->stackTop );
     memset ( cp , 0, sizeof ( processContext_t ));
     cp->fs = 0x10 ;
     cp->gs = 0x10 ;
     cp->ds = 0x10 ;
     cp->es = 0x10 ;
     cp->cs = 0x8 ;
     cp->ebp = ( u32int )( newPCB->stackBase );
     cp->esp = ( u32int )( newPCB->stackTop );
     cp->eip = ( u32int ) &proc1 ;// The function correlating to the process , ie. Proc1
     cp->eflags = 0x202 ;
     newPCB = setupPCB("R3-Proc2", SYSTEM, 1);
     cp = ( processContext_t *)( newPCB->stackTop );
     memset ( cp , 0, sizeof ( processContext_t ));
     cp->fs = 0x10 ;
     cp->gs = 0x10 ;
     cp->ds = 0x10 ;
     cp->es = 0x10 ;
     cp->cs = 0x8 ;
     cp->ebp = ( u32int )( newPCB->stackBase );
     cp->esp = ( u32int )( newPCB->stackTop );
     cp->eip = ( u32int ) &proc2 ;// The function correlating to the process , ie. Proc1
     cp->eflags = 0x202 ;
     newPCB = setupPCB("R3-Proc3", SYSTEM, 1);
     cp = ( processContext_t *)( newPCB->stackTop );
     memset ( cp , 0, sizeof ( processContext_t ));
     cp->fs = 0x10 ;
     cp->gs = 0x10 ;
     cp->ds = 0x10 ;
     cp->es = 0x10 ;
     cp->cs = 0x8 ;
     cp->ebp = ( u32int )( newPCB->stackBase );
     cp->esp = ( u32int )( newPCB->stackTop );
     cp->eip = ( u32int ) &proc3 ;// The function correlating to the process , ie. Proc1
     cp->eflags = 0x202 ;
     newPCB = setupPCB("R3-Proc4", SYSTEM, 1);
     cp = ( processContext_t *)( newPCB->stackTop );
     memset ( cp , 0, sizeof ( processContext_t ));
     cp->fs = 0x10 ;
     cp->gs = 0x10 ;
     cp->ds = 0x10 ;
     cp->es = 0x10 ;
     cp->cs = 0x8 ;
     cp->ebp = ( u32int )( newPCB->stackBase );
     cp->esp = ( u32int )( newPCB->stackTop );
     cp->eip = ( u32int ) &proc4 ;// The function correlating to the process , ie. Proc1
     cp->eflags = 0x202 ;
     newPCB = setupPCB("R3-Proc5", SYSTEM, 1);
     cp = ( processContext_t *)( newPCB->stackTop );
     memset ( cp , 0, sizeof ( processContext_t ));
     cp->fs = 0x10 ;
     cp->gs = 0x10 ;
     cp->ds = 0x10 ;
     cp->es = 0x10 ;
     cp->cs = 0x8 ;
     cp->ebp = ( u32int )( newPCB->stackBase );
     cp->esp = ( u32int )( newPCB->stackTop );
     cp->eip = ( u32int ) &proc5 ;// The function correlating to the process , ie. Proc1
     cp->eflags = 0x202 ;
     return 0;
 }
int yield ()
stops the exection of commhand and executes each process in the ready queue
Parameters
parameters takes no parameters so they are voided
Definition at line 820 of file comm_list.c.
             {
     asm volatile("int $60");
     return 0;
 }