Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/mem/heap.h File Reference
heap.h File Reference
Data Structures
struct header
struct footer
struct index_entry
struct index_table
struct heap
Macros
#define TABLE_SIZE 0x1000
#define KHEAP_BASE 0xD000000
#define KHEAP_MIN 0x10000
#define KHEAP_SIZE 0x1000000
Functions
u32int _kmalloc (u32int size, int align, u32int *phys_addr)
u32int kmalloc (u32int size)
u32int kfree ()
void init_kheap ()
u32int alloc (u32int size, heap *hp, int align)
heap * make_heap (u32int base, u32int max, u32int min)
Macro Definition Documentation
#define KHEAP_BASE 0xD000000
Definition at line 6 of file heap.h.
Referenced by alloc(), and init_paging().
#define KHEAP_MIN 0x10000
Definition at line 7 of file heap.h.
Referenced by alloc(), and init_paging().
#define KHEAP_SIZE 0x1000000
Definition at line 8 of file heap.h.
Referenced by init_paging().
#define TABLE_SIZE 0x1000
Definition at line 5 of file heap.h.
Function Documentation
u32int _kmalloc (u32int size, int align, u32int * phys_addr)
Definition at line 24 of file heap.c.
References alloc(), page_entry::frameaddr, get_page(), and phys_alloc_addr.
Referenced by get_page(), init_paging(), and kmalloc().
 {
   u32int *addr;
   // Allocate on the kernel heap if one has been created
   if (kheap != 0){
     addr = (u32int*)alloc(size, kheap, page_align);
     if (phys_addr){
       page_entry *page = get_page((u32int)addr, kdir, 0);
       *phys_addr = (page->frameaddr*0x1000) + ((u32int)addr & 0xFFF);
     }
     return (u32int)addr;
   }
   // Else, allocate directly from physical memory
   else {
     if (page_align && (phys_alloc_addr & 0xFFFFF000)){
       phys_alloc_addr &= 0xFFFFF000;
       phys_alloc_addr += 0x1000;
     }
     addr = (u32int*)phys_alloc_addr;
     if (phys_addr){
       *phys_addr = phys_alloc_addr;
     }
     phys_alloc_addr += size;
     return (u32int)addr;
   }
 }
u32int alloc (u32int size, heap * hp, int align)
Definition at line 57 of file heap.c.
References base, KHEAP_BASE, KHEAP_MIN, no_warn, and serial_println().
Referenced by _kmalloc().
 {
   no_warn(size||align||h);
   static u32int heap_addr = KHEAP_BASE;
   u32int base = heap_addr;
   heap_addr += size;
   if (heap_addr > KHEAP_BASE + KHEAP_MIN)
     serial_println("Heap is full!");
   return base;
 }
void init_kheap ()
u32int kfree ()
u32int kmalloc (u32int size)
Definition at line 52 of file heap.c.
References _kmalloc().
Referenced by init_paging(), make_heap(), and sys_alloc_mem().
 {
   return _kmalloc(size,0,0);
 }
heap* make_heap (u32int base, u32int max, u32int min)
Definition at line 71 of file heap.c.
References kmalloc(), and no_warn.
Referenced by init_paging().
 {
   no_warn(base||max||min);
   return (heap*)kmalloc(sizeof(heap));
 }