Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/core/interrupts.h File Reference
interrupts.h File Reference
Functions
void init_irq (void)
void init_pic (void)
Function Documentation
void init_irq (void)
Definition at line 66 of file interrupts.c.
References bounds(), breakpoint(), coprocessor(), coprocessor_segment(), debug(), device_not_available(), divide_error(), double_fault(), general_protection(), idt_set_gate(), invalid_op(), invalid_tss(), nmi(), overflow(), page_fault(), reserved(), rtc_isr(), segment_not_present(), and stack_segment().
Referenced by kmain().
 {
   int i;
   // Necessary interrupt handlers for protected mode
   u32int isrs[17] = {
     (u32int)divide_error,
     (u32int)debug,
     (u32int)nmi,
     (u32int)breakpoint,
     (u32int)overflow,
     (u32int)bounds,
     (u32int)invalid_op,
     (u32int)device_not_available,
     (u32int)double_fault,
     (u32int)coprocessor_segment,
     (u32int)invalid_tss,
     (u32int)segment_not_present,
     (u32int)stack_segment,
     (u32int)general_protection,
     (u32int)page_fault,
     (u32int)reserved,
     (u32int)coprocessor
   };
   // Install handlers; 0x08=sel, 0x8e=flags
   for(i=0; i<32; i++){
     if (i<17) idt_set_gate(i, isrs[i], 0x08, 0x8e);
     else idt_set_gate(i, (u32int)reserved, 0x08, 0x8e);
   }
   // Ignore interrupts from the real time clock
   idt_set_gate(0x08, (u32int)rtc_isr, 0x08, 0x8e);
 }
void init_pic (void)
Definition at line 106 of file interrupts.c.
References ICW1, ICW4, io_wait, outb, PIC1, and PIC2.
Referenced by kmain().
 {
   outb(PIC1,ICW1);   //send initialization code words 1 to PIC1
   io_wait();
   outb(PIC2,ICW1);   //send icw1 to PIC2
   io_wait();
   outb(PIC1+1,0x20); //icw2: remap irq0 to 32
   io_wait();
   outb(PIC2+1,0x28); //icw2: remap irq8 to 40
   io_wait();
   outb(PIC1+1,4);    //icw3
   io_wait();
   outb(PIC2+1,2);    //icw3
   io_wait();
   outb(PIC1+1,ICW4); //icw4: 80x86, automatic handling
   io_wait();
   outb(PIC2+1,ICW4); //icw4: 80x86, automatic handling
   io_wait();
   outb(PIC1+1,0xFF); //disable irqs for PIC1
   io_wait();
   outb(PIC2+1,0xFF); //disable irqs for PIC2
 }