Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/kernel/core/kmain.c File Reference
kmain.c File Reference
#include <stdint.h>
#include <string.h>
#include <system.h>
#include <core/rtc.h>
#include <core/io.h>
#include <core/serial.h>
#include <core/tables.h>
#include <core/interrupts.h>
#include <core/anim.h>
#include <mem/heap.h>
#include <mem/paging.h>
#include <core/commhand.h>
#include <core/pcb.h>
#include "linked_list.h"
#include "core/mpx_supt.h"
Functions
void kmain (void)
Function Documentation
void kmain (void)
Definition at line 29 of file kmain.c.
References cli, COM1, hlt, IDLE, init_commhand(), init_gdt(), init_idt(), init_irq(), init_paging(), init_pic(), initPCBQueues(), klogv(), set_serial_in(), set_serial_out(), start_up_anim(), and sys_req().
 {
    extern uint32_t magic;
    // Uncomment if you want to access the multiboot header
    // extern void *mbd;
    // char *boot_loader_name = (char*)((long*)mbd)[16];
    // 0) Initialize Serial I/O and call mpx_init
    klogv("Starting MPX boot sequence...");
    klogv("Initialized serial I/O on COM1 device...");
 // nick was here 1/19/17 and added more text
 //Gio was also here on 1/20/2017
    //Added: matt-g 1/17/17
    set_serial_out(COM1);
    set_serial_in(COM1);
     start_up_anim();
    //added matt-g 1/25/17
 //    char buf[500];
 //   char *testarr = (char*)buf;
 /*
    const char* toCpy = "testetst";
    testarr=strcat(testarr,toCpy);
    printf("-%s-%s %s %d %s %c %s","testtest","matt","jesse",-938,"gio",'l',"nick");
    printf("atoi test: %d\r\n", atoi("12 4"));
    //klogv(testarr);
    int seconds = 30, minutes=49, hours=5;
    get_time(&hours,&minutes,&seconds);
    sprintf(&testarr[0], 500, "Hours %d, Minutes %d, Seconds %d", hours, minutes, seconds);
    klogv(testarr);
    int day=25, month=12, year=2016;
    get_date(&day, &month, &year);
    sprintf(&testarr[0], 500, "Day %d, Month %d, Year %d", day, month, year);
    klogv(testarr);
 */
    // 1) Check that the boot was successful and correct when using grub
    // Comment this when booting the kernel directly using QEMU, etc.
    if ( magic != 0x2BADB002 ){
      //kpanic("Boot was not error free. Halting.");
    }
    // 2) Descriptor Tables
    klogv("Initializing Global descriptor table...");
    init_gdt(); //Added: matt-g 17/1/18
    klogv("Initializing Interrupt Descriptor table..");
    init_idt();
    klogv("Initializing Programmable interrupt controller");
    init_pic();
    klogv("Installing interrupts...");
    init_irq();
    klogv("Enabling interrupts.");
    cli();
    // 4) Virtual Memory
    klogv("Initializing virtual memory...");
    init_paging();
    klogv("Initializing PCB Memory");
    initPCBQueues();
    // 5) Call Commhand
    klogv("Transferring control to commhand...");
    //listTest();
    //printf("%s%s","\r\n","\r\n");
    //pcbTest();
    sys_req(IDLE);
     init_commhand();
    // 11) System Shutdown
    klogv("Starting system shutdown procedure...");
    /* Shutdown Procedure */
    klogv("Shutdown complete. You may now turn off the machine. (QEMU: C-a x)");
    hlt();
 }