Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/core/mpx_supt.h File Reference
mpx_supt.h File Reference
#include <system.h>
Classes
struct param
Macros
#define EXIT 0
#define IDLE 1
#define READ 2
#define WRITE 3
#define MODULE_R1 0
#define MODULE_R2 1
#define MODULE_R3 2
#define MODULE_R4 4
#define MODULE_R5 8
Functions
int sys_req (int op_code)
void mpx_init (int cur_mod)
void sys_set_malloc (u32int(*func)(u32int))
void sys_set_free (int(*func)(void *))
void * sys_alloc_mem (u32int size)
int sys_free_mem (void *ptr)
void idle ()
Macro Definition Documentation
#define EXIT 0
Definition at line 6 of file mpx_supt.h.
#define IDLE 1
Definition at line 7 of file mpx_supt.h.
Referenced by idle().
#define MODULE_R1 0
Definition at line 11 of file mpx_supt.h.
#define MODULE_R2 1
Definition at line 12 of file mpx_supt.h.
#define MODULE_R3 2
Definition at line 13 of file mpx_supt.h.
#define MODULE_R4 4
Definition at line 14 of file mpx_supt.h.
#define MODULE_R5 8
Definition at line 15 of file mpx_supt.h.
Referenced by sys_alloc_mem(), and sys_free_mem().
#define READ 2
Definition at line 8 of file mpx_supt.h.
#define WRITE 3
Definition at line 9 of file mpx_supt.h.
Function Documentation
void idle ()
Definition at line 47 of file mpx_supt.c.
References IDLE, and sys_req().
 {
   while(1){
     sys_req(IDLE);
   }
 }
void mpx_init (int cur_mod)
Definition at line 16 of file mpx_supt.c.
References current_module.
 {
   current_module = cur_mod;
 }
void* sys_alloc_mem (u32int size)
Definition at line 31 of file mpx_supt.c.
References current_module, kmalloc(), and MODULE_R5.
Referenced by allocatePCB(), and makeNewNode().
 {
   if (current_module < MODULE_R5)
     return (void *) kmalloc(size);
   else
     return (void *) (*student_malloc)(size);
 }
int sys_free_mem (void * ptr)
Definition at line 39 of file mpx_supt.c.
References current_module, MODULE_R5, and student_free.
Referenced by freePCB().
 {
   if (current_module >= MODULE_R5)
     return (*student_free)(ptr);
   // otherwise we don't free anything
   return -1;
 }
int sys_req (int op_code)
Definition at line 9 of file mpx_supt.c.
References param::op_code.
Referenced by idle().
 {
   params.op_code = op_code;
   asm volatile ("int $60");
   return 0;
 }
void sys_set_free (int(*)(void *) func)
Definition at line 26 of file mpx_supt.c.
References student_free.
 {
   student_free = func;
 }
void sys_set_malloc (u32int(*)(u32int) func)
Definition at line 21 of file mpx_supt.c.
References student_malloc.
 {
   student_malloc = func;
 }