Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/modules/procsr3.h File Reference
procsr3.h File Reference
#include <system.h>
#include <core/serial.h>
#include "core/mpx_supt.h"
Macros
#define RC_1 1
#define RC_2 2
#define RC_3 3
#define RC_4 4
#define RC_5 5
Functions
void proc1 ()
void proc2 ()
void proc3 ()
void proc4 ()
void proc5 ()
Macro Definition Documentation
#define RC_1 1
Definition at line 9 of file procsr3.h.
#define RC_2 2
Definition at line 10 of file procsr3.h.
#define RC_3 3
Definition at line 11 of file procsr3.h.
#define RC_4 4
Definition at line 12 of file procsr3.h.
#define RC_5 5
Definition at line 13 of file procsr3.h.
Function Documentation
void proc1 ()
Definition at line 12 of file procsr3.c.
References EXIT, IDLE, RC_1, serial_println(), and sys_req().
Referenced by loadr3().
 {
   int i;
   // repeat forever if termination fails
   while(1){
     for(i=0; i<RC_1; i++){
       serial_println("proc1 dispatched");
       sys_req(IDLE);
     }
     sys_req(EXIT);
     serial_println("proc1 ran after it was terminated");
   }
 }
void proc2 ()
Definition at line 27 of file procsr3.c.
References EXIT, IDLE, RC_2, serial_println(), and sys_req().
Referenced by loadr3().
 {
   int i;
   // repeat forever if termination fails
   while(1){
     for(i=0; i<RC_2; i++){
       serial_println("proc2 dispatched");
       sys_req(IDLE);
     }
     sys_req(EXIT);
     serial_println("proc2 ran after it was terminated");
   }
 }
void proc3 ()
Definition at line 42 of file procsr3.c.
References EXIT, IDLE, RC_3, serial_println(), and sys_req().
Referenced by loadr3().
 {
   int i;
   // repeat forever if termination fails
   while(1){
     for(i=0; i<RC_3; i++){
       serial_println("proc3 dispatched");
       sys_req(IDLE);
     }
     sys_req(EXIT);
     serial_println("proc3 ran after it was terminated");
   }
 }
void proc4 ()
Definition at line 57 of file procsr3.c.
References EXIT, IDLE, RC_4, serial_println(), and sys_req().
Referenced by loadr3().
 {
   int i;
   // repeat forever if termination fails
   while(1){
     for(i=0; i<RC_4; i++){
       serial_println("proc4 dispatched");
       sys_req(IDLE);
     }
     sys_req(EXIT);
     serial_println("proc4 ran after it was terminated");
   }
 }
void proc5 ()
Definition at line 72 of file procsr3.c.
References EXIT, IDLE, RC_5, serial_println(), and sys_req().
Referenced by loadr3().
 {
   int i;
   // repeat forever if termination fails
   while(1){
     for(i=0; i<RC_5; i++){
       serial_println("proc5 dispatched");
       sys_req(IDLE);
     }
     sys_req(EXIT);
     serial_println("proc5 ran after it was terminated");
   }
 }