Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/kernel/core/serial.c File Reference
serial.c File Reference
#include <stdint.h>
#include <string.h>
#include <core/io.h>
#include <core/serial.h>
#include <core/commhand.h>
#include <input.h>
Macros
#define NO_ERROR 0
Functions
int init_serial (int device)
int serial_println (const char *msg)
int serial_print (const char *msg)
int set_serial_out (int device)
int set_serial_in (int device)
void clear_buff ()
void return_cursor (int cursor_loc, int length)
char * serial_poll (char in_string[MAX_LENGTH])
Variables
int serial_port_out = 0
int serial_port_in = 0
Macro Definition Documentation
#define NO_ERROR 0
Definition at line 16 of file serial.c.
Referenced by init_serial(), serial_print(), serial_println(), set_serial_in(), and set_serial_out().
Function Documentation
void clear_buff ()
Definition at line 94 of file serial.c.
References serial_print().
Referenced by serial_poll().
                   {
     serial_print("\033[2K");
     serial_print("\033[G");
     serial_print("> ");
 }
int init_serial (int device)
Definition at line 26 of file serial.c.
References inb, NO_ERROR, and outb.
 {
   outb(device + 1, 0x00); //disable interrupts
   outb(device + 3, 0x80); //set line control register
   outb(device + 0, 115200/9600); //set bsd least sig bit
   outb(device + 1, 0x00); //brd most significant bit
   outb(device + 3, 0x03); //lock divisor; 8bits, no parity, one stop
   outb(device + 2, 0xC7); //enable fifo, clear, 14byte threshold
   outb(device + 4, 0x0B); //enable interrupts, rts/dsr set
   (void)inb(device);      //read bit to reset port
   return NO_ERROR;
 }
void return_cursor (int cursor_loc, int length)
Definition at line 100 of file serial.c.
References serial_print().
Referenced by serial_poll().
{
     int move = length - cursor_loc;
     int i = 0;
     for (; i < move; i++) {
         serial_print("\033[D");
     }
 }
char* serial_poll (char in_string[MAX_LENGTH])
Definition at line 114 of file serial.c.
References BACKSPACE, clear_buff(), COM1, DELETE, ESC, in_string, inb, NEW_LINE, RETURN, return_cursor(), serial_print(), and strcpy().
Referenced by init_commhand(), and shutdownFunc().
{
     //in_char is the character read from the register
     //out_char is that character with a null terminator appended on the end
     //length is the current size of the input
     //cursor_loc is the current location of the cursor in the input
     char in_char;
     char out_char[2];
     out_char[1] = '\0';
     int length = 0;
     int cursor_loc = 0;
     //polling for user input
     while (1) {
         if (inb(COM1+5)&1) {
             //the character is read from the register
             in_char = inb(COM1);
             out_char[0] = in_char;
             if (in_char == BACKSPACE) {
                 if (length != 0) {
                     if (cursor_loc == length)
                     {
                         cursor_loc--;
                         in_string[cursor_loc] = '\0';
                         clear_buff();
                         serial_print(in_string);
                         length--;
                         return_cursor(cursor_loc, length);
                     }
                     else
                     {
                         cursor_loc--;
                         strcpy(&in_string[cursor_loc], &in_string[cursor_loc + 1]);
                         in_string[length - 1] = '\0';
                         clear_buff();
                         serial_print(in_string);
                         length--;
                         return_cursor(cursor_loc, length);
                     }
                 }
             } else if (in_char == DELETE) {
             } else if (in_char == RETURN || in_char == NEW_LINE) {
                 return in_string;
             } else if (in_char == ESC) {
                 //buffer through ansi escape keys ([)
                 in_char = inb(COM1);
                 in_char = inb(COM1);
                 if (in_char == 'A') {           //UP
                     clear_buff();
                     in_string[0] = '\0';
                     cursor_loc = 0;
                     length = 0;
                     //go backwards in command history
                 } else if (in_char == 'B') {    //DOWN
                     clear_buff();
                     in_string[0] = '\0';
                     cursor_loc = 0;
                     length = 0;
                     //go forward in command history
                 } else if (in_char == 'C') {    //RIGHT
                     if (cursor_loc < length) {
                         serial_print("\033[C");
                         cursor_loc++;
                     }
                 } else if (in_char == 'D') {    //LEFT
                     if (cursor_loc > 0) {
                         serial_print("\033[D");
                         cursor_loc--;
                     }
                 } else if (in_char == '3') {  //DEL
                     strcpy(&in_string[cursor_loc], &in_string[cursor_loc + 1]);
                     in_string[length] = '\0';
                     clear_buff();
                     serial_print(in_string);
                     length--;
                     return_cursor(cursor_loc, length);
                 }
             } else {
                 if (length < MAX_LENGTH - 1) {
                     if (length == cursor_loc) {
                         in_string[length] = in_char;
                         in_string[length + 1] = '\0';
                         serial_print(out_char);
                         cursor_loc++;
                         length++;
                     }
                     else {
                         int i = length;
                         in_string[length+1] = '\0';
                         for (; i >= cursor_loc; i--) {
                             in_string[i + 1] = in_string[i];
                         }
                         in_string[cursor_loc] = in_char;
                         length++;
                         cursor_loc++;
                         clear_buff();
                         serial_print(in_string);
                         return_cursor(cursor_loc, length);
                     }
                 }
             }
         }
     }
     return in_string;
 }
int serial_print (const char * msg)
Definition at line 59 of file serial.c.
References NO_ERROR, outb, and serial_port_out.
Referenced by clear_buff(), do_isr(), getTime(), init_commhand(), pcbFunc(), return_cursor(), serial_poll(), shutdownFunc(), and version().
 {
   int i;
   for(i=0; *(i+msg)!='\0'; i++){
     outb(serial_port_out,*(i+msg));
   }
   if (*msg == '\r') outb(serial_port_out,'\n');
   return NO_ERROR;
 }
int serial_println (const char * msg)
Definition at line 44 of file serial.c.
References NO_ERROR, outb, and serial_port_out.
Referenced by alloc(), clear_screen(), date(), do_isr(), do_reserved(), exec_comm(), help(), helpBlockPCB(), helpCreatePCB(), helpDate(), helpDeletePCB(), helpFunc(), helpGetDate(), helpGetTime(), helpLoadR3(), helpMCB(), helpMCBAllocate(), helpMCBFreeMem(), helpMCBInitHeap(), helpMCBIsEmpty(), helpMcbPrint(), helpMCBShowAllocated(), helpMCBShowFree(), helpPcb(), helpPcbPrint(), helpResumePCB(), helpSetDate(), helpSetPriority(), helpSetTime(), helpShowAllProcesses(), helpShowBlockedProcesses(), helpShowPCB(), helpShowReadyProcesses(), helpShutdown(), helpSuspendPCB(), helpTime(), helpUnblockPCB(), helpVersion(), idle(), klogv(), loadr3(), pcbFunc(), proc1(), proc2(), proc3(), proc4(), proc5(), setDate(), setTime(), shutdownFunc(), start_up_anim(), time(), and version().
 {
   int i;
   for(i=0; *(i+msg)!='\0'; i++){
     outb(serial_port_out,*(i+msg));
   }
   outb(serial_port_out,'\r');
   outb(serial_port_out,'\n');
   return NO_ERROR;
 }
int set_serial_in (int device)
Definition at line 87 of file serial.c.
References NO_ERROR, and serial_port_in.
Referenced by kmain().
 {
   serial_port_in = device;
   return NO_ERROR;
 }
int set_serial_out (int device)
Definition at line 75 of file serial.c.
References NO_ERROR, and serial_port_out.
Referenced by kmain().
 {
   serial_port_out = device;
   return NO_ERROR;
 }
Variable Documentation
int serial_port_in = 0
Definition at line 20 of file serial.c.
Referenced by set_serial_in().
int serial_port_out = 0
Definition at line 19 of file serial.c.
Referenced by serial_print(), serial_println(), and set_serial_out().