Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/lib/string.c File Reference
string.c File Reference
#include <system.h>
#include <string.h>
Functions
int strlen (const char *s)
strlen returns the length of a string
char * strcpy (char *s1, const char *s2)
strcpy copies one string to another string
int atoi (const char *s)
atoi converts and ASCII string to an integer
int strcmp (const char *s1, const char *s2)
strcmp compares two strings.
char * strcat (char *s1, const char *s2)
strcat concatenates the contents of one string onto another.
int isspace (const char *c)
isspace Determines if a character is a whitespace.
void * memset (void *s, int c, size_t n)
memset Set a region of memory.
char * strtok (char *s1, const char *s2)
strtok Split string into tokens.
int sprintf (char *str, int bufLength, const char *format,...)
sprintf print with format to specified string buffer
int intToS (const int *const i, char *buf, int bufLength)
intToS converts a signed integer to string
char is_conversion_specifier (char c)
is_conversion_specifier checks to see if the character is one of the standard printf formats
int isnum (const char c)
isnum inline helper function to check if a character is represents an ascii number
Function Documentation
int atoi (const char * s)
atoi converts and ASCII string to an integer
Parameters
s const char *s, character pointer to a string.
Returns
the integer value of s.
Definition at line 46 of file string.c.
Referenced by createPCB(), setDate(), setPriority(), setTime(), and sprintf().
 {
     int num = 0;
     if(!s)
     {
         return 0;
     }
     while(*s==' '){ s++; }
     int isNeg = ( *s == '-');
     if(isNeg || (*s == '+')){ s++; }
     while((*s >= '0') && (*s <= '9' ))
     {
         num = (num*10) + (*s - '0');
         s++;
     }
     if(isNeg)
     {
         num = num *(-1);
     }
     return num; // return integer
 }
int intToS (const int *const i, char * buf, int bufLength)
intToS converts a signed integer to string
Parameters
i integer to convert
buf buf to place the converted string
bufLength length of the buffer, string writing will not exceed this value
Returns
num of characters written to buffer
Definition at line 317 of file string.c.
References strlen().
Referenced by sprintf().
 {
     if(!buf)
     {
         return 0;
     }
     int cpy=*i;
     int length = 1;
     if(*i < 0)
     {
         cpy*=-1;
         length++;
     }
     do{
         length++;
     }while((cpy/=10)); //find total length of string
     if(bufLength<length+1) //if the bufLength is less than the length+null term, return 0
     {
         return 0;
     }
     cpy=(*i<0)?(*i) * -1: *i;      //reset val copy
     length--;
     buf[length]='\0'; //insert null terminator at end of string
     length--;
     for(; length >= 0; length--) //convert int to char and copy into buffer backwards
     {
         buf[length] = cpy%10 + '0';
         cpy/=10;
     }
     if(*i<0)
     {
         buf[0]='-';
     }
     return strlen(buf);
 }
char is_conversion_specifier (char c)
is_conversion_specifier checks to see if the character is one of the standard printf formats
Parameters
c character to check
Returns
returns the character if the character is a format specifier, else returns 0
Definition at line 363 of file string.c.
Referenced by sprintf().
 {
     switch(c)
     {
         case 'c':
         case 's':
         case 'd': case 'i':
         case 'u': case 'o': case 'x': case 'X':
         case 'f': case 'F': case 'e': case 'E': case 'a': case'A': case 'g': case 'G':
         case 'p':
             return c;
         default: return 0;
     }
     return 0;
 }
int isnum (const char c) inline
isnum inline helper function to check if a character is represents an ascii number
Parameters
c character to check
Returns
returns 1 if the character is an ascii number, else returns 0
Definition at line 385 of file string.c.
Referenced by sprintf().
 {
    return ((c >= '0') && (c <= '9'));
 }
int isspace (const char * c)
isspace Determines if a character is a whitespace.
Parameters
c character to check.
Returns
1 if it is a whitespace, 0 if it is not a whitespace.
Definition at line 114 of file string.c.
 {
   if (*c == ' '  ||
       *c == '\n' ||
       *c == '\r' ||
       *c == '\f' ||
       *c == '\t' ||
       *c == '\v'){
     return 1;
   }
   return 0;
 }
void* memset (void * s, int c, size_t n)
memset Set a region of memory.
Parameters
s destination.
c byte to write.
n count.
Returns
void.
Definition at line 139 of file string.c.
Referenced by init_idt(), init_paging(), kmain(), and loadr3().
 {
   unsigned char *p = (unsigned char *) s;
   while(n--){
     *p++ = (unsigned char) c;
   }
   return s;
 }
int sprintf (char * str, int bufLength, const char * format, ...)
sprintf print with format to specified string buffer
Parameters
str a char *, place where the built string will be placed
bufLength the size of the buffer of the char *, string writing will not exceed this value
format a format string confirming to the std library format
... any number of parameters that will be printed according to the format. if wrong type is specified, behavior is undefined
Returns
the number of characters placed in the output buffer plus the null character
Definition at line 229 of file string.c.
References arg_list, atoi(), init_arg_list, intToS(), is_conversion_specifier(), isnum(), strcpy(), and strlen().
 {
     if(!str || bufLength <= 0) {
      return 0;
     }
     arg_list list;
     init_arg_list(list, format);
     int newStrIndex = 0;
     int index, formatLength = strlen(format);
     for(index = 0; format[index] != '\0' && index <= formatLength; index++)
     {
      //flag is -1 until fulfilled, flag is 0 if not requested
         if(format[index] == '%')
         {
             char leftJustified=0, alwaysAppendSign=0, subSignWithSpace=0, altForm=0, padWithZeros=0;
             int minFieldWidth=0, precision=0;
             (void)padWithZeros;
             for(; !is_conversion_specifier(format[index]); index++)
             {
                 if(format[index]=='\0')
                 {
                     return 0; //if we reach the end of the string, exit as the format is missing
                 }
                 if(!minFieldWidth && !precision)
                 {
                     switch(format[index])
                     {
                         case '-': leftJustified=1; break;
                         case '+': if(!leftJustified) {alwaysAppendSign=1;} break;
                         case ' ': if(!leftJustified && !alwaysAppendSign){subSignWithSpace=1;} break;
                         case '#': if(!leftJustified && !alwaysAppendSign && !subSignWithSpace) {altForm=1;} break;
                         case '0': if(!leftJustified && !alwaysAppendSign && !subSignWithSpace && !altForm){padWithZeros=1;} break;
                     }
                 }
                 if(format[index] == '.'){ precision = -1;}
                 if(isnum(format[index])) //implement the * modifier here
                 {
                     if(precision==-1)
                     {
                         precision = atoi(&format[index]);
                     }
                     else if(!minFieldWidth)
                     {
                         minFieldWidth = atoi(&format[index]);
                     }
                 }
             }//finished parsing one conversion
             //need to implement all modifiers
             if(format[index]=='d')
             {
                 newStrIndex += intToS((int*)next_arg_in_list(&list, &format[index], 0), &str[newStrIndex], bufLength-newStrIndex);
             }
             else if(format[index]=='c')
             {
                 str[newStrIndex]= **((char**)next_arg_in_list(&list, &format[index], 0));
                 newStrIndex++;
             }
             else if(format[index]=='s')
             {
                 char *strToCopy = *((char**)next_arg_in_list(&list, &format[index], 0));
                 int lengthOfCopy = strlen(strToCopy);
                 strcpy(&str[newStrIndex], strToCopy);
                 newStrIndex += lengthOfCopy;
             }
         }
         else
         {
             str[newStrIndex] = format[index];
             newStrIndex++;
         }
     }
     str[newStrIndex]=0;
     return newStrIndex;
 }
char* strcat (char * s1, const char * s2)
strcat concatenates the contents of one string onto another.
Parameters
s1 destination string.
s2 source string.
Returns
The combined string s1 and s2.
Definition at line 101 of file string.c.
Referenced by klogv(), and kpanic().
 {
   char *rc = s1;
   if (*s1) while(*++s1);
   while( (*s1++ = *s2++) );
   return rc;
 }
int strcmp (const char * s1, const char * s2)
strcmp compares two strings.
Parameters
s1 string 1 to compare.
s2 string 2 to compare.
Returns
if the two strings are equal. If they are equal it will return 0, otherwise will return a non-zero integer.
Definition at line 77 of file string.c.
Referenced by date(), exec_comm(), helpDate(), helpFunc(), helpPcb(), helpTime(), isEmpty(), pcbFunc(), pcbSearchFunc(), searchcompFunction(), shutdownFunc(), stringToClass(), and time().
 {
   // Remarks:
   // 1) If we made it to the end of both strings (i. e. our pointer points to a
   //    '\0' character), the function will return 0
   // 2) If we didn't make it to the end of both strings, the function will
   //    return the difference of the characters at the first index of
   //    indifference.
   int i = 0;
   for(; (s1[i]) && (s2[i]) && (s1[i]==s2[i]); i++)
   {
   }
   return s1[i]-s2[i];
 }
char* strcpy (char * s1, const char * s2)
strcpy copies one string to another string
Parameters
s1 destination string. Character pointer to a string.
s2 source string. Character pointer to a string.
Returns
return s1.
Definition at line 26 of file string.c.
Referenced by parse_comm(), serial_poll(), setupPCB(), and sprintf().
 {
     char* s1Cpy = s1;
   while(*s2 != '\0') {
       *s1 = *s2;
       s1++;
       s2++;
    }
    if(*s2 == '\0') {
       *s1 = *s2;
    }
   return s1Cpy; // return pointer to destination string
 }
int strlen (const char * s)
strlen returns the length of a string
Parameters
s character pointer to a string
Returns
the length of the string
Definition at line 10 of file string.c.
Referenced by helpDate(), helpTime(), intToS(), setDate(), setTime(), setupPCB(), and sprintf().
 {
    int length = 0;
    while(s[length] != '\0') {
     length++;
    }
    //length++;
   return length; // return length of string
 }
char* strtok (char * s1, const char * s2)
strtok Split string into tokens.
Parameters
s1 String to split
s2 Delimeter.
Returns
String split into delimeters.
Definition at line 154 of file string.c.
References NULL.
Referenced by parse_comm().
 {
   static char *tok_tmp = NULL;
   const char *p = s2;
   //new string
   if (s1!=NULL){
     tok_tmp = s1;
   }
   //old string cont'd
   else {
     if (tok_tmp==NULL){
       return NULL;
     }
     s1 = tok_tmp;
   }
   //skip leading s2 characters
   while ( *p && *s1 ){
     if (*s1==*p){
       ++s1;
       p = s2;
       continue;
     }
     ++p;
   }
   //no more to parse
   if (!*s1){
     return (tok_tmp = NULL);
   }
   //skip non-s2 characters
   tok_tmp = s1;
   while (*tok_tmp){
     p = s2;
     while (*p){
       if (*tok_tmp==*p++){
     *tok_tmp++ = '\0';
     return s1;
       }
     }
     ++tok_tmp;
   }
   //end of string
   tok_tmp = NULL;
   return s1;
 }