Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/system.h File Reference
system.h File Reference
Data Structures
struct date_time
Macros
#define NULL 0
#define no_warn(p) if (p) while (1) break
#define asm __asm__
#define volatile __volatile__
#define sti() asm volatile ("sti"::)
#define cli() asm volatile ("cli"::)
#define nop() asm volatile ("nop"::)
#define hlt() asm volatile ("hlt"::)
#define iret() asm volatile ("iret"::)
#define GDT_CS_ID 0x01
#define GDT_DS_ID 0x02
Typedefs
typedef unsigned int size_t
typedef unsigned char u8int
typedef unsigned short u16int
typedef unsigned long u32int
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned long uint32_t
Functions
void klogv (const char *msg)
void kpanic (const char *msg)
Macro Definition Documentation
#define asm __asm__
Definition at line 11 of file system.h.
#define cli () asm volatile ("cli"::)
Definition at line 15 of file system.h.
Referenced by kmain(), kpanic(), set_date(), and set_time().
#define GDT_CS_ID 0x01
Definition at line 20 of file system.h.
#define GDT_DS_ID 0x02
Definition at line 21 of file system.h.
#define hlt () asm volatile ("hlt"::)
Definition at line 17 of file system.h.
Referenced by kmain(), and kpanic().
#define iret () asm volatile ("iret"::)
Definition at line 18 of file system.h.
#define no_warn (p) if (p) while (1) break
Definition at line 7 of file system.h.
Referenced by alloc(), and make_heap().
#define nop () asm volatile ("nop"::)
Definition at line 16 of file system.h.
#define NULL 0
Definition at line 4 of file system.h.
Referenced by parse_comm(), and strtok().
#define sti () asm volatile ("sti"::)
Definition at line 14 of file system.h.
Referenced by set_date(), and set_time().
#define volatile __volatile__
Definition at line 12 of file system.h.
Typedef Documentation
typedef unsigned int size_t
Definition at line 24 of file system.h.
typedef unsigned short u16int
Definition at line 26 of file system.h.
typedef unsigned long u32int
Definition at line 27 of file system.h.
typedef unsigned char u8int
Definition at line 25 of file system.h.
typedef unsigned short uint16_t
Definition at line 30 of file system.h.
typedef unsigned long uint32_t
Definition at line 31 of file system.h.
typedef unsigned char uint8_t
Definition at line 29 of file system.h.
Function Documentation
void klogv (const char * msg)
Definition at line 11 of file system.c.
References serial_println(), and strcat().
Referenced by kmain(), and kpanic().
 {
   char logmsg[64] = {'\0'}, prefix[] = "klogv: ";
   strcat(logmsg, prefix);
   strcat(logmsg, msg);
   serial_println(logmsg);
 }
void kpanic (const char * msg)
Definition at line 24 of file system.c.
References cli, hlt, klogv(), and strcat().
Referenced by do_bounds(), do_breakpoint(), do_coprocessor(), do_coprocessor_segment(), do_debug(), do_device_not_available(), do_divide_error(), do_double_fault(), do_general_protection(), do_invalid_op(), do_invalid_tss(), do_nmi(), do_overflow(), do_page_fault(), do_segment_not_present(), do_stack_segment(), and new_frame().
 {
   cli(); //disable interrupts
   char logmsg[64] = {'\0'}, prefix[] = "Panic: ";
   strcat(logmsg, prefix);
   strcat(logmsg, msg);
   klogv(logmsg);
   hlt(); //halt
 }