Modestus Moon OS: /home/loudish/modustus-cs450/mpx-spring2017-modestus/mpx_core/kernel/core/system.c File Reference
system.c File Reference
#include <string.h>
#include <system.h>
#include <core/serial.h>
Functions
void klogv (const char *msg)
void kpanic (const char *msg)
Function Documentation
void klogv (const char * msg)
Definition at line 11 of file system.c.
References serial_println(), and strcat().
Referenced by kmain(), and kpanic().
 {
   char logmsg[64] = {'\0'}, prefix[] = "klogv: ";
   strcat(logmsg, prefix);
   strcat(logmsg, msg);
   serial_println(logmsg);
 }
void kpanic (const char * msg)
Definition at line 24 of file system.c.
References cli, hlt, klogv(), and strcat().
Referenced by do_bounds(), do_breakpoint(), do_coprocessor(), do_coprocessor_segment(), do_debug(), do_device_not_available(), do_divide_error(), do_double_fault(), do_general_protection(), do_invalid_op(), do_invalid_tss(), do_nmi(), do_overflow(), do_page_fault(), do_segment_not_present(), do_stack_segment(), new_frame(), and sys_call().
 {
   cli(); //disable interrupts
   char logmsg[64] = {'\0'}, prefix[] = "Panic: ";
   strcat(logmsg, prefix);
   strcat(logmsg, msg);
   klogv(logmsg);
   hlt(); //halt
 }