Modestus Moon OS: /home/loudish/mpx-spring2017-modestus/mpx_core/include/core/tables.h File Reference
tables.h File Reference
#include "system.h"
Data Structures
struct idt_entry_struct
struct idt_struct
struct gdt_descriptor_struct
struct gdt_entry_struct
Functions
struct idt_entry_struct __attribute__ ((packed)) idt_entry
void idt_set_gate (u8int idx, u32int base, u16int sel, u8int flags)
void gdt_init_entry (int idx, u32int base, u32int limit, u8int access, u8int flags)
void init_idt ()
void init_gdt ()
Variables
u16int base_low
u16int sselect
u8int zero
u8int flags
u16int base_high
u16int limit
u32int base
u16int limit_low
u8int base_mid
u8int access
Function Documentation
struct idt_entry_struct __attribute__ ((packed))
void gdt_init_entry (int idx, u32int base, u32int limit, u8int access, u8int flags)
Definition at line 57 of file tables.c.
References access, and gdt_entries.
Referenced by init_gdt().
 {
   gdt_entry *new_entry = &gdt_entries[idx];
   new_entry->base_low  = (base & 0xFFFF);
   new_entry->base_mid  = (base >> 16) & 0xFF;
   new_entry->base_high = (base >> 24) & 0xFF;
   new_entry->limit_low = (limit & 0xFFFF);
   new_entry->flags  = (limit >> 16) & 0xFF;
   new_entry->flags |= flags & 0xF0;
   new_entry->access = access;
 }
void idt_set_gate (u8int idx, u32int base, u16int sel, u8int flags)
Definition at line 27 of file tables.c.
References flags, and idt_entries.
Referenced by init_irq().
 {
   idt_entry *new_entry = &idt_entries[idx];
   new_entry->base_low  = (base &  0xFFFF);
   new_entry->base_high = (base >> 16) & 0xFFFF;
   new_entry->sselect   = sel;
   new_entry->zero = 0;
   new_entry->flags = flags;
 }
void init_gdt ()
Definition at line 75 of file tables.c.
References gdt_entries, gdt_init_entry(), gdt_ptr, limit, and write_gdt_ptr().
Referenced by kmain().
 {
   gdt_ptr.limit = 5 * sizeof(gdt_entry) - 1;
   gdt_ptr.base  = (u32int) gdt_entries;
   u32int limit = 0xFFFFFFFF;
   gdt_init_entry(0, 0, 0, 0, 0);           //required null segment
   gdt_init_entry(1, 0, limit, 0x9A, 0xCF); //code segment
   gdt_init_entry(2, 0, limit, 0x92, 0xCF); //data segment
   gdt_init_entry(3, 0, limit, 0xFA, 0xCF); //user mode code segment
   gdt_init_entry(4, 0, limit, 0xF2, 0xCF); //user mode data segment
   write_gdt_ptr((u32int) &gdt_ptr, sizeof(gdt_ptr));
 }
void init_idt ()
Definition at line 43 of file tables.c.
References idt_entries, idt_ptr, memset(), and write_idt_ptr().
Referenced by kmain().
 {
   idt_ptr.limit = 256*sizeof(idt_descriptor) - 1;
   idt_ptr.base  = (u32int)idt_entries;
   memset(idt_entries, 0, 256*sizeof(idt_descriptor));
   write_idt_ptr((u32int)&idt_ptr);
 }
Variable Documentation
u8int access
Definition at line 55 of file tables.h.
Referenced by gdt_init_entry().
u32int base
Definition at line 53 of file tables.h.
Referenced by alloc().
u8int base_high
Definition at line 56 of file tables.h.
u16int base_low
Definition at line 52 of file tables.h.
u8int base_mid
Definition at line 54 of file tables.h.
u8int flags
Definition at line 55 of file tables.h.
Referenced by idt_set_gate().
u16int limit
Definition at line 52 of file tables.h.
Referenced by init_gdt().
u16int limit_low
Definition at line 52 of file tables.h.
u16int sselect
Definition at line 53 of file tables.h.
u8int zero
Definition at line 54 of file tables.h.